### pruebas para obtener TODOS los usuarios (con get):
GET http://localhost:3000/api/usuarios

### pruebas para obtener UN usuario:

GET http://localhost:3000/api/usuarios/cub45-328-777-0000-0000

### pruebas para crear un nuevo usuario:
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "name": "Carlos",
  "esAdmin": false,
  "estaActivo": true
}

### modificar un usuario (PUT o PATCH): el put debe ser idempotente, es decir, si se hace varias veces el resultado debe ser el mismo. El patch no es idempotente, ya que cada vez que se hace la petición se modifica el recurso.
PUT http://localhost:3000/api/usuarios/cub45-328-777-0000-0000
Content-Type: application/json

{
  "name": "Ignacio",
  "esAdmin": false,
  "estaActivo": true
}

### modificar un usuario (PATCH - recurso parcial):
PATCH  http://localhost:3000/api/usuarios/cub45-328-777-0000-0000
Content-Type: application/json

{
  "name": "Shifu",
  "esAdmin": true,
  "estaActivo": true
}
