### pruebas para obtener TODOS los usuarios (con get):
GET http://localhost:3000/api/usuarios

### pruebas para obtener UN usuario:

GET http://localhost:3000/api/usuarios/cub45-328-777-0000-0000

### pruebas para crear un nuevo usuario:
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "name": "Carlos",
  "esAdmin": false,
  "estaActivo": true
}
